bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
rvm:
  - jruby-9.2.9.0
  - truffleruby-head
  - ruby-head
  - ruby-head-clang
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
matrix:
  include:
    - rvm: jruby-9.1.17.0
      env: BUNDLER_VERSION=2.0.2
    - rvm: 2.5.5
      gemfile: gemfiles/Gemfile.public_suffix_2
    - rvm: 2.5.7
      env: IDNA_MODE=native
      script: bundle exec rake profile:memory
      name: "Profile Memory Allocation with native IDNA"
    - rvm: 2.5.7
      env: IDNA_MODE=pure
      script: bundle exec rake profile:memory
      name: "Profile Memory Allocation with pure Ruby IDNA"
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang
  fast_finish: true
before_install:
  - sudo apt-get update
  - sudo apt-get install libidn11-dev
  # https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - if [ -n "${BUNDLER_VERSION+x}" ];
    then
      gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true;
      gem uninstall --all --executables bundler || true;
      gem install bundler -v ${BUNDLER_VERSION};
    fi
